name: konda_app
description: In the sector of Information Technology. Cyber-crime is hiking day by day there is not have anyone to control and authenticate them. Mostly educated people want to know details about any company, organization, individual person they do mostly use internet but why? Because they want to same own valuable time, they trust to the internet, they believe in the internet surely have right information but they were wrong. The demands of internet growing every day that is excellent that’s why KONDA have launches semi trance authentication techniques using full of rights.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  flutter_gen: ^1.3.1
  animations: ^1.1.2
  flutter_swiper: ^1.1.6
  flutter_statusbarcolor: ^0.2.3
  flutter_session: ^0.1.1
  videos_player: ^0.1.3
  line_awesome_flutter: ^1.0.1
  flutter_screenutil: ^1.0.2
  animated_theme_switcher: ^1.0.9
  flutter_spinkit: ^4.1.2+1
  intro_slider: ^2.3.3
  shared_preferences: ^0.5.12+4
  retrofit_generator: ^1.4.1+1
  build_runner: ^1.10.11
  jwt_decoder: ^1.0.3
  retrofit: ^1.3.4+1
  http: ^0.12.2
  url_launcher: ^5.7.10
  lottie: ^0.7.0+1
  share: ^0.6.0+1
  fluttertoast: ^3.0.4
  avatar_glow: ^0.1.0
  bottom_navy_bar: ^5.6.0
  flutter_windowmanager: ^0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_share: ^1.0.5
  documents_picker: ^1.0.0
  image_picker: ^0.6.7+22
  image_cropper: ^1.3.1
  provider: ^4.3.3
  carousel_slider: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
